site_name: Rethink Engine

repo_url: https://github.com/jammees/Rethink-Engine
repo_name: jammees/Rethink-Engine

theme:
  # initial settings
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png

  # set theme
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  # features
  features:
    - navigation.tabs
    - search.highlight
    - search.suggest
    - content.code.copy
    - navigation.footer

markdown_extensions:
  - attr_list
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

extra_css:
  - stylesheets/colors.css
  - stylesheets/extra.css

# setup navigation
nav:
  - Home: index.md
  - Get started:
    - Installation: getstarted/installation.md
    - Changelog: getstarted/changelog.md
  - Documentation:
    - Rethink: documentation/rethink.md
    - Animator: documentation/animator.md
    - Camera: documentation/camera.md
    - Scene: documentation/scene.md
    - Outline: documentation/outline.md
    - Template: documentation/template.md
    - Settings: documentation/settings.md
    - 3rd Party Modules: documentation/3rdpartymodules.md
