name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  Changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          src:
            - 'src/**'

  Selene:
    needs: Changes
    if: ${{ needs.Changes.outputs.src == 'true' }}
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Foreman
      uses: Roblox/setup-foreman@v1
      with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Selene on src
      run: selene src
  
  StyLua:
    needs: Changes
    if: ${{ needs.Changes.outputs.src == 'true' }}
    name: Style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Foreman
      uses: Roblox/setup-foreman@v1
      with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run StyLua on src
      run: stylua src --check
