name: Deploy docs

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write

jobs:
    Changes:
      runs-on: ubuntu-latest
      permissions:
        contents: read
      outputs:
        docs: ${{ steps.filter.outputs.docs }}
      steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'

    Deploy:
        needs: Changes
        if: ${{ needs.Changes.outputs.docs == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                python-version: '3.11.1'
                cache: 'pip'

            - run: pip install mkdocs-material
            - run: mkdocs gh-deploy